### PR TITLE
Fix: Home Card CodeCombat click handleClick function error

### PR DESCRIPTION
**Pull request by FeynmanDNA**
I was still getting the error even after the "quickfix home links #371". So I added a handler to the invocation of handleClick function. 

Now Codecombat card onClick will open a new tab/window, and the other cards' onClick will work fine as well.

### CODE REVIEW

**Comment by Brainenjii** [comment]
just tried at https://achievements-dev.firebaseapp.com/ -  it works for me fine

**Comment by FeynmanDNA** [comment]
@Brainenjii you are right. I revert the change locally and this time there is no error...

I don't know what happened over there. I will close this PR.

**Comment by Brainenjii** [comment]
why? this change is working also

**Comment by Brainenjii** [comment]
```
class RecommendationCard {
..
  handleClick () {
    const {activity} = this.props; // <- here context will be lost with `onClick={this.handleClick}`
  handleClick = () => {
    const {activity} = this.props; // <- here context will be passed with `onClick={this.handleClick}`
```
`() => this.handleClick()` - provides `this` context in both variants

**Pull request merged**
