### PR TITLE
 fix: advanced activities

### PR DESCRIPTION
**Pull request by Brainenjii**
Rename Local Tasks to Advanced Activities at UI.
Disable `Commit` button for advanced activities unless solution
will be solved

REF: https://github.com/NUS-ALSET/achievements/issues/783

### CODE REVIEW

**Comment by Ourstress** [comment]
Hi @Brainenjii, i couldn't get the commit button to be disabled even when my lambda function sends back isComplete:False in it's body. Could I trouble you to check? thanks!

**Comment by Brainenjii** [comment]
Hello, @Ourstress! Could you show your lambda function URL or JSON response body?

**Comment by Ourstress** [comment]
Hey @Brainenjii , thanks for your reply! It's https://nykwr7dphi.execute-api.us-east-1.amazonaws.com/default/CodeCombatCustomActivity

**Comment by Brainenjii** [comment]
@Ourstress could you also show example of valid request? I tried use my CodeCombat login  and https://codecombat.com/play/level/queen-of-the-desert as `map url` but I got `"solution format incorrect"` as response

**Comment by Ourstress** [comment]
Sure, use the username soreto

**Comment by Brainenjii** [comment]
@Ourstress oh, it seems like something went wrong :-( I get 500 error now :-(

**Comment by Ourstress** [comment]
oops sorry i added some code to the function that wasn't supposed to be there- working now

**Comment by Brainenjii** [comment]
image
@Ourstress thx! It works now. But I still got `solution format incorrect`. What should I write at map url?

**Comment by Ourstress** [comment]
sorry for the wording - the mapurl part should contain the username and mapurl
soreto, https://codecombat.com/play/level/queen-of-the-desert

**Comment by Brainenjii** [comment]
@Ourstress ok, found. There is a bug at the completeness check code. If there is `jsonFeedback` field then only `solved` field is being considered :-( I'll fix that

**Comment by Ourstress** [comment]
thanks a lot @Brainenjii 
sorry for the trouble!

**Comment by Brainenjii** [comment]
@Ourstress that's fine :-) Thx for noticing!

**Pull request merged**
